# -*- coding: utf-8 -*-
"""GS.SERS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-9XVVV281UGWnmZPWxmGTKtP6Y-SDsDf
"""

import random
import time

nome_missao = "ORION-X"
status_missao = "OPERACIONAL"

modulos = {
"Propulsao": "ATIVO",
"Oxigenio": "ATIVO",
"Comunicacao": "ATIVO",
"Painel Solar": "ATIVO",
"Navegacao": "ATIVO"
}

def gerar_dados():

  dados = {
    "temperatura": random.randint(20, 120),
    "energia": random.randint(10, 100),
    "potencia": random.randint(100, 1000),
    "energia_solar": random.randint(0, 100),
    "comunicacao": random.choice([True, False])
}

  return dados

def verificar_alertas(dados):

  alertas = []

  if dados["temperatura"] > 80:
    alertas.append("Temperatura alta")

  if dados["energia"] < 30:
    alertas.append("Energia baixa")

  if dados["comunicacao"] == False:
    alertas.append("Sem comunicacao")

  if dados["energia_solar"] < 20:
    alertas.append("Sem captação solar")

  return alertas

def inteligencia_artificial(dados):

    respostas = []

    if dados["temperatura"] > 80:
        respostas.append("IA: Sistema de resfriamento ativado")

    if dados["energia"] < 30:
        respostas.append("IA: Modo economia ativado")

    if dados["comunicacao"] == False:
        respostas.append("IA: Reiniciando antena principal")

    if dados["energia_solar"] < 20:
        respostas.append("IA: Redirecionando paineis solares")

    return respostas

def analisar_sustentabilidade(dados):


    if dados["energia_solar"] >= 70:
        return "Excelente eficiencia energetica renovavel"

    elif dados["energia_solar"] >= 40:
        return "Boa eficiencia energetica"

    else:
        return "Baixa eficiencia energetica"

def verificar_modulos(dados):

    if dados["temperatura"] > 100:
        modulos["Propulsao"] = "FALHA"
    else:
        modulos["Propulsao"] = "ATIVO"

    if dados["energia"] < 20:
        modulos["Painel Solar"] = "SOBRECARGA"

    else:
        modulos["Painel Solar"] = "ATIVO"

    if dados["comunicacao"] == False:
        modulos["Comunicacao"] = "OFFLINE"

    else:
        modulos["Comunicacao"] = "ONLINE"

def exibir_painel(dados):

  print("\n================================================")
  print("CENTRAL DE CONTROLE ESPACIAL")
  print("MISSAO:", nome_missao)
  print("STATUS:", status_missao)
  print("================================================")

  print(f"Temperatura: {dados['temperatura']} °C")
  print(f"Energia: {dados['energia']} %")
  print(f"Potencia: {dados['potencia']} W")
  print(f"Energia Solar: {dados['energia_solar']} %")

  if dados["comunicacao"]:
      print("Comunicacao: ONLINE")
  else:
      print("Comunicacao: OFFLINE")

  print("\nSTATUS DOS MODULOS")

  for modulo, status in modulos.items():
      print(f"{modulo}: {status}")

def gerar_relatorio(alertas, respostas, sustentabilidade):

  print("\n================================================")
  print("RELATORIO OPERACIONAL")
  print("================================================")

  # ALERTAS
  print("\nALERTAS GERADOS")

  if len(alertas) == 0:
      print("Nenhum alerta encontrado")

  else:
      for alerta in alertas:
          print(alerta)

  # IA
  print("\nACOES AUTOMATIZADAS")

  if len(respostas) == 0:
      print("Nenhuma acao necessaria")

  else:
      for resposta in respostas:
          print(resposta)

  # SUSTENTABILIDADE
  print("\nANALISE ENERGETICA")
  print(sustentabilidade)

# SISTEMA PRINCIPAL

# =========================================================

print("INICIANDO SISTEMA DA MISSAO...")
time.sleep(2)

# EXECUTA 5 CICLOS DE MONITORAMENTO

for ciclo in range(5):

    print(f"\n############ CICLO {ciclo + 1} ############")

    # GERA DADOS
    dados = gerar_dados()

    # VERIFICA MÓDULOS
    verificar_modulos(dados)

    # GERA ALERTAS
    alertas = verificar_alertas(dados)

    # IA
    respostas = inteligencia_artificial(dados)

    # SUSTENTABILIDADE
    sustentabilidade = analisar_sustentabilidade(dados)

    # EXIBE PAINEL
    exibir_painel(dados)

    # RELATÓRIO
    gerar_relatorio(alertas, respostas, sustentabilidade)

    # ESPERA
    time.sleep(3)


# =========================================================

# FINALIZAÇÃO

# =========================================================

print("\n================================================")
print("MISSAO ENCERRADA")
print("Sistema finalizado com sucesso")